from __future__ import annotations

"""Real procedural biome texture synthesis: bakes a heightmap + its biome
classification into actual exportable basecolor and roughness PNG maps.

Detail is generated by real coherent fractal value noise -- domain-warped
biome boundaries (so edges are organic, not grid-aligned blocks from the
coarse heightmap grid) plus multi-octave coherent color/roughness variation
within each biome (not flat blocks, and not uniform per-pixel white-noise
static either) -- so output quality scales with texture_size independent of
the underlying heightmap's own resolution_power.

Deterministic and seeded, same discipline as app.world.terrain -- no
external texture/model/noise-library dependency, real local numpy
computation only.
"""

from pathlib import Path

import numpy as np
from PIL import Image

from app.world.biomes import Biome, BiomeThresholds, classify_biomes

# Per-biome (base_rgb, color_jitter, base_roughness, roughness_jitter).
# *_jitter is the max deviation applied by real coherent fractal noise, not a
# cosmetic label -- this is what keeps output from looking like flat,
# obviously-synthetic color blocks.
_BIOME_TEXTURE_PARAMS: dict[str, tuple[tuple[int, int, int], int, float, float]] = {
    Biome.WATER.value: ((30, 80, 160), 18, 0.05, 0.03),
    Biome.BEACH.value: ((210, 190, 140), 22, 0.55, 0.10),
    Biome.PLAINS.value: ((90, 140, 60), 28, 0.75, 0.12),
    Biome.FOREST.value: ((35, 90, 40), 30, 0.80, 0.12),
    Biome.ROCK.value: ((110, 100, 95), 25, 0.65, 0.15),
    Biome.MOUNTAIN.value: ((140, 130, 125), 24, 0.60, 0.15),
    Biome.SNOW.value: ((240, 240, 245), 12, 0.35, 0.08),
}


def _value_noise_2d(size: int, *, frequency: int, seed: int) -> np.ndarray:
    """Bilinearly-interpolated lattice value noise on a (size, size) grid in
    [-1, 1], `frequency` lattice cells per axis. Real coherent noise (smooth,
    continuous between lattice points), not per-pixel white noise -- the
    building block for both domain warping and fractal detail below."""
    frequency = max(1, frequency)
    rng = np.random.default_rng(seed)
    lattice = rng.uniform(-1.0, 1.0, size=(frequency + 1, frequency + 1))

    coords = np.linspace(0, frequency, size, endpoint=False)
    x0 = coords.astype(np.int64)
    fx = coords - x0
    gy, gx = np.meshgrid(x0, x0, indexing="ij")
    fgy, fgx = np.meshgrid(fx, fx, indexing="ij")

    top_left = lattice[gy, gx]
    top_right = lattice[gy, gx + 1]
    bottom_left = lattice[gy + 1, gx]
    bottom_right = lattice[gy + 1, gx + 1]

    top = top_left * (1 - fgx) + top_right * fgx
    bottom = bottom_left * (1 - fgx) + bottom_right * fgx
    return top * (1 - fgy) + bottom * fgy


def _fractal_noise_2d(size: int, *, base_frequency: int, octaves: int, seed: int) -> np.ndarray:
    """Sum of _value_noise_2d at doubling frequency and halving amplitude
    (standard fBm construction), normalized to [-1, 1]."""
    total = np.zeros((size, size), dtype=np.float64)
    amplitude = 1.0
    max_amplitude = 0.0
    for octave in range(octaves):
        total += amplitude * _value_noise_2d(size, frequency=base_frequency * (2 ** octave), seed=seed + octave * 977)
        max_amplitude += amplitude
        amplitude *= 0.5
    return total / max_amplitude


def _domain_warped_biome_labels(heightmap: np.ndarray, texture_size: int, seed: int, thresholds) -> np.ndarray:
    """Upsample the (coarse) biome grid to (texture_size, texture_size) via
    nearest-neighbor lookup, but at coordinates perturbed by real coherent
    noise first -- so biome boundaries in the output texture are organic and
    wavy rather than following the heightmap grid's own cell edges, which is
    what makes a directly-upsampled coarse grid look artificially blocky
    regardless of how large texture_size is."""
    labels = classify_biomes(heightmap, thresholds)
    n = labels.shape[0]

    warp_x = _fractal_noise_2d(texture_size, base_frequency=6, octaves=3, seed=seed + 1001)
    warp_y = _fractal_noise_2d(texture_size, base_frequency=6, octaves=3, seed=seed + 2002)
    # Warp amplitude scaled relative to the coarse grid's own cell size, so
    # boundaries wander by roughly one grid cell -- enough to be organic
    # without displacing a biome region beyond its neighbors.
    warp_amplitude = (n / texture_size) * 1.5 if texture_size > 0 else 0.0

    base_coords = np.linspace(0, n - 1, texture_size)
    gy, gx = np.meshgrid(base_coords, base_coords, indexing="ij")
    warped_y = np.clip(gy + warp_y * warp_amplitude, 0, n - 1).round().astype(np.int64)
    warped_x = np.clip(gx + warp_x * warp_amplitude, 0, n - 1).round().astype(np.int64)

    return labels[warped_y, warped_x]


def synthesize_biome_basecolor(
    heightmap: np.ndarray,
    *,
    texture_size: int,
    seed: int = 0,
    thresholds: BiomeThresholds | None = None,
) -> np.ndarray:
    """Returns a (texture_size, texture_size, 3) uint8 RGB array: organic,
    domain-warped biome boundaries, with real coherent fractal-noise color
    variation within each biome (mottled, natural detail -- not flat blocks,
    not uniform per-pixel static)."""
    if heightmap.ndim != 2 or heightmap.shape[0] != heightmap.shape[1]:
        raise ValueError("heightmap must be a square 2D array")
    if texture_size < 1:
        raise ValueError("texture_size must be >= 1")

    labels_tex = _domain_warped_biome_labels(heightmap, texture_size, seed, thresholds)

    # Three independent coherent-noise channels (distinct seeds) at a fine
    # base frequency scaled to texture_size, so detail density -- not just
    # pixel count -- increases with texture_size.
    base_freq = max(4, texture_size // 16)
    noise_r = _fractal_noise_2d(texture_size, base_frequency=base_freq, octaves=4, seed=seed + 10)
    noise_g = _fractal_noise_2d(texture_size, base_frequency=base_freq, octaves=4, seed=seed + 20)
    noise_b = _fractal_noise_2d(texture_size, base_frequency=base_freq, octaves=4, seed=seed + 30)

    rgb = np.zeros((texture_size, texture_size, 3), dtype=np.float64)
    for biome_value, (base_rgb, jitter, _rough, _rough_jitter) in _BIOME_TEXTURE_PARAMS.items():
        mask = labels_tex == biome_value
        if not mask.any():
            continue
        rgb[..., 0][mask] = base_rgb[0] + noise_r[mask] * jitter
        rgb[..., 1][mask] = base_rgb[1] + noise_g[mask] * jitter
        rgb[..., 2][mask] = base_rgb[2] + noise_b[mask] * jitter

    return np.clip(rgb, 0, 255).astype(np.uint8)


def synthesize_biome_roughness(
    heightmap: np.ndarray,
    *,
    texture_size: int,
    seed: int = 0,
    thresholds: BiomeThresholds | None = None,
) -> np.ndarray:
    """Returns a (texture_size, texture_size) uint8 grayscale roughness map,
    with the same domain-warped boundaries and coherent fractal-noise detail
    as the basecolor map (distinct noise seed, so roughness and color detail
    aren't perfectly correlated pixel-for-pixel)."""
    if heightmap.ndim != 2 or heightmap.shape[0] != heightmap.shape[1]:
        raise ValueError("heightmap must be a square 2D array")
    if texture_size < 1:
        raise ValueError("texture_size must be >= 1")

    labels_tex = _domain_warped_biome_labels(heightmap, texture_size, seed, thresholds)
    base_freq = max(4, texture_size // 16)
    noise = _fractal_noise_2d(texture_size, base_frequency=base_freq, octaves=4, seed=seed + 40)

    roughness = np.zeros((texture_size, texture_size), dtype=np.float64)
    for biome_value, (_rgb, _jitter, base_rough, rough_jitter) in _BIOME_TEXTURE_PARAMS.items():
        mask = labels_tex == biome_value
        if not mask.any():
            continue
        roughness[mask] = base_rough + noise[mask] * rough_jitter

    return np.clip(roughness, 0.0, 1.0).__mul__(255).astype(np.uint8)


def export_biome_texture_maps(
    heightmap: np.ndarray,
    *,
    texture_size: int,
    basecolor_path: str | Path,
    roughness_path: str | Path,
    seed: int = 0,
    thresholds: BiomeThresholds | None = None,
) -> dict[str, str]:
    """Synthesize both maps and write them as real PNG files. Returns the
    written paths, so the caller (or a downstream QA step like
    app.qa.textures.inspect_texture) has real files to verify against."""
    basecolor = synthesize_biome_basecolor(heightmap, texture_size=texture_size, seed=seed, thresholds=thresholds)
    roughness = synthesize_biome_roughness(heightmap, texture_size=texture_size, seed=seed, thresholds=thresholds)

    basecolor_path = Path(basecolor_path)
    roughness_path = Path(roughness_path)
    basecolor_path.parent.mkdir(parents=True, exist_ok=True)
    roughness_path.parent.mkdir(parents=True, exist_ok=True)

    Image.fromarray(basecolor, mode="RGB").save(basecolor_path)
    Image.fromarray(roughness, mode="L").save(roughness_path)

    return {"basecolor_path": str(basecolor_path), "roughness_path": str(roughness_path)}
